= Dossier d’Analyse et de Conception
:toc:
:toc-title: Sommaire

Version de l'application : 1 +
Date : 20/04/2022 +
Client : BankUniv +
Projet : Daily Bank + 

<<<

== 1. Description du Projet
=== a) Equipe

Conception/Développement : Marcq Galatée - Monté Hugo - Tubia Eva +

=== b) Contexte du projet

Daily Bank est un réseau français de 100 agences bancaires. Il est nécessaire pour eux de restructurer leur réseau afin de s’intégrer dans une stratégie de différenciation. Ils possèdent plusieurs outils qui deviennent obsolètes et une première version d’application qui nécessite une refonte. Les besoins de la banque ont évolués, tout comme ceux de leurs clients, il faut donc développer plusieurs fonctinnalités pour répondre à ces nouveaux besoins.

=== c) Objectifs du projet

Le but est de partir d’une application existante et d’y rajouter des fonctionnalités. Il y a deux types d’utilisateurs de l’application : le guichetier et le chef d’agence. Les guichetiers pourront créer de nouveaux clients et faire les opérations courantes (Create Read Update Delete). Les chefs d’agences pourront gérer les employés et les opérations exeptionnelles. L’application sera découpée en plusieurs versions (3) à la demande du client.

== 2. Architecture

=== a) Architecture Générale

=== b) Ressources externes

=== c) Structuration en packages

=== d) Élements essentiels

== 3. Fonctionnalités

=== a) Version 1

==== Créditer un compte (Eva Tubia)

Use case : "Créditer un compte" +
Accessibilité : Guichetier et Chef d'agence +

Action de création d'une opération crédit sur un compte. +
Fonctionnement dans le code : lorsque l'utilisateur clique sur le bouton "Enregistrer crédit ", le contrôleur de vue `OperationsManagementController` transfère les informations nécessaires au contrôle `OperationsManagement`  pour l'affichage de la page. Ensuite, pour enregistrer le crédit, la classe contrôle `OperationEditorPane` est utilisée, elle va afficher la page pour créer l'opération et transmettre les informations au controleur de vue `OperationEditorPaneController`. Les entrées de l'utilisateur sont controlées lorsqu'il tente de valider l'opération, si tout est correct l'opération est créée et le contrôle `OperationsManagement` peut enfin se connecter à la base de données et effectuer l'opération si l'opération n'est pas nulle. L'opération dans la base de données est effectué en utilisant la classe ORM `AccessOperation`. +

Conditions de validation de l'opération : Montant entré non null, positif, correspondant à un entier +

==== Virement de compte à compte (Eva Tubia)

Use case : "Effectuer un virement de compte à compte" +
Accessibilité : Guichetier et Chef d'agence +

Action de création d'une opération virement entre deux comptes. +
Fonctionnement dans le code : lorsque l'utilisateur clique sur le bouton "Effectuer un virement ", le contrôleur de vue `OperationsManagementController` transfère les informations nécessaires au contrôle `OperationsManagement`  pour l'affichage de la page. Ensuite, pour enregistrer le virement, la classe contrôle `OperationEditorPane` est utilisée, elle va afficher la page pour créer l'opération et transmettre les informations au controleur de vue `OperationEditorPaneController`. Les entrées de l'utilisateur sont controlées lorsqu'il tente de valider l'opération, si tout est correct deux opérations sont crées, l'une correspondant au compte qui effectue le virement (débit) et l'autre correspondant au compte destinataire (crédit). Ces deux opérations sont transmises au controle `OperationsManagement` qui peut enfin se connecter à la base de données et effectuer les opérations en utilisant la classe ORM `AccessOperation`. +

Conditions de validation de l'opération : Montant entré non null, positif, correspondant à un entier, ne dépassant pas le débit autorisé / Numéro de compte entré non null, existant, non cloturé +

==== Créer un compte (Hugo Monté)

Use case : "Créer un compte"

(Attente image DC : joindre table CompteCourant)

Action d'insertion du nouveau compte dans cette table. +
Fonctionnement dans le code : le contrôleur de vue ComptesManagement transfère l'information de création (pour ouvrir le menu qui affiche les données à saisir) au contrôle ComptesManagement qui va afficher l'interface puis envoyer l'information de création à l'ORM AccesCompteCourant et renvoyer le résultat après tout ça au contrôleur de vue initial. AccesCompteCourant va appeler CreerCompte dans la base de données.

Informations supplémentaires sur la documentation utilisateur.

==== Clôturer un compte (Hugo Monté)

Use case : "Clôturer un compte"

(Attente image DC : joindre table CompteCourant : solde, estCloture)

Action de modification sur cette table de "solde" et de "estCloture" (respectivement 0 et "O"). +
Fonctionnement dans le code : le contrôleur de vue ComptesManagement transfère l'information de clôture au contrôle ComptesManagement qui va envoyer l'information de clôture à l'ORM AccesCompteCourant et renvoyer le résultat après tout ça au contrôleur de vue initial. AccesCompteCourant va modifier "estCloture" de ce compte pour mettre "O" (signifiant oui) ainsi que le solde (remis à 0) dans la base de données.

Informations supplémentaires sur la documentation utilisateur.

=== b) Version 2

=== c) Version 3

