@startuml issue1

usecase a as "Modifier informations client"
usecase b as "Créer un nouveau client"
usecase c as "Consulter un compte"
usecase d as "Débiter un compte (BD)"
usecase e as "Rendre inactif un client"

actor Guichetier 
actor Chef_agence 

Guichetier <|-- Chef_agence

Guichetier --> a
Guichetier --> b
Guichetier --> c
Guichetier --> d
Chef_agence --> e

@enduml
