@startuml tp

hide circle
hide empty members




skinparam classAttributeIconSize 0

skinparam roundcorner 5

skinparam class {
	BackgroundColor FFFEC0
	BorderColor C92D2D
	ArrowColor C92D2D
	FontColor Black
	FontSize 12
	FontName Helvetica
}

skinparam arrow {
    MessageAlign center
}

class Roues {

}

class Voiture {
	couleur
	modele
	start()
	run()
	stop()
}

class Moteur {}

class Chauffeur {}

Voiture *-left- "4" Roues
Voiture *-- "1" Moteur
Roues "2..4" -- "0..1" Moteur : controler
Voiture "0..*" -- "0..1" Chauffeur : conduire

@enduml
