= Manuel d'utilisation de l'application
:toc:
:toc-title: Sommaire

Version de l'application : 1 +
Date : 20/04/2022 +
Equipe : Marcq Galatée - Monté Hugo - Tubia Eva +
Client : BankUniv +
Projet : Daily Bank + 

<<<

== 1. Description du Projet
=== a) Equipe

Conception/Développement : Marcq Galatée - Monté Hugo - Tubia Eva +

=== b) Contexte du projet

Daily Bank est un réseau français de 100 agences bancaires. Il est nécessaire pour eux de restructurer leur réseau afin de s’intégrer dans une stratégie de différenciation. Ils possèdent plusieurs outils qui deviennent obsolètes et une première version d’application qui nécessite une refonte. Les besoins de la banque ont évolués, tout comme ceux de leurs clients, il faut donc développer plusieurs fonctinnalités pour répondre à ces nouveaux besoins.

=== c) Objectifs du projet

Le but est de partir d’une application existante et d’y rajouter des fonctionnalités. Il y a deux types d’utilisateurs de l’application : le guichetier et le chef d’agence. Les guichetiers pourront créer de nouveaux clients et faire les opérations courantes (Create Read Update Delete). Les chefs d’agences pourront gérer les employés et les opérations exeptionnelles. L’application sera découpée en plusieurs versions (3) à la demande du client.

== 2. Lancer l'application
=== a) Prérequis

L'application DailyBankApp nécessite d'avoir installé Java 1.8. Si vous avez d'autres versions de Java installées, il faut lancer votre cmd en Java 1.8. +

=== b) Lancer le fichier jar
Si vous n'avez que la version 1.8 de Java, double cliquez sur le fichier DayliBank.jar pour lancer l'application. Si vous avez plusieurs versions de Java, ouvrez votre cmd dans le dossier où se trouve le fichier jar et éxecutez la commande suivante `java -jar DailyBank.jar` .

== 3. Utiliser l'application

=== a) Explications des rôles
=== b) Guichetier

==== Créer un compte

Pour créer un compte, le guichetier doit ouvrir le menu des comptes du client concerné puis cliquer sur "Nouveau compte" et enfin saisir les informations de ce nouveau compte. Une fois la création effectuée, ce compte apparaît dans la liste immédiatement (à moins qu'une erreur ait été mentionnée à la création).

==== Clôturer un compte

Pour clôturer un compte, le guichetier doit ouvrir le menu des comptes du client concerné, sélectionner le compte concerné et enfin cliquer sur "Supprimer compte". Le bouton est disponible si un compte est sélectionné et que ce dernier n'est pas déjà clôturé. Cela a pour effet de mettre le solde à 0 et le définiir comme clôturé (ces changements prennent effet immédiatement sur l'interface).

=== c) Chef d'agence
